import './globals.css'
import type { Metadata } from 'next'
import { Chakra_Petch } from 'next/font/google'

const chacka = Chakra_Petch({
  weight: '400',
  style: 'normal',
  preload: true,
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={`bg-fixed bg-gradient-to-r from-green to-blue-500 dark:from-dark-500 dark:to-dark-700 dark:text-white ${chacka.className}`}>
          {children}
      </body>
    </html>
  )
}